### ISSUE TITLE
Inactive repo? -- What is remaining for a proper 1.0.0 release?

### ISSUE THREAD

**Issue by Zageron** [michiel/jsonapi-rust#82]
It doesn't appear that there has been much activity on this repo. If additional maintainers aren't added should it be forked or is there a better alternative? @mmstick @michiel @ducharmemp @JadedEvan @genbattle

**Comment by michiel** [comment]
Hi @Zageron I'm still actively using this crate, but haven't looked at changing it much recently. I'm happy to add maintainers in the short term and discuss a longer term plan. Are any participants interested?

**Comment by Zageron** [comment]
> 
> 
> Hi @Zageron I'm still actively using this crate, but haven't looked at changing it much recently. I'm happy to add maintainers in the short term and discuss a longer term plan. The way it's currently set up is that any maintainer has all relevant privileges and can bump the version and add a tag, which automatically gets published to crates.io, etc. Are any participants interested?

Thanks so much for your quick reply!

I only noted this because there are 5 active PRs. I'll start using the crate and if I find that I like it I may participate.
